apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ggg222999/firstgo:latest
