---
- gather_facts: false
  remote_user: root
  vars:
    version: "{{version}}"
    ansible_ssh_private_key_file: "/var/lib/jenkins/.ssh/id_rsa"
  tasks:
    - name: copying service.yml playbook
      become: true 
      copy:
        src: /tmp/service.yml
        dest: /tmp
    - name: copying deployment.yml playbook
      become: true
      copy:
        src: /tmp/deployment.yml
        dest: /tmp
    - name: Deploy the service
      k8s:
        state: present
        src: /tmp/service.yml
        validate_certs: no
        namespace: default
    - name: Deploy the application
      k8s:
        state: present
        src: /tmp/deployment.yml
        validate_certs: no
        namespace: default
