---
- hosts: masternode
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: "/var/lib/jenkins/.ssh/id_rsa"
  tasks:
    - name: Deploy the service
      k8s:
        state: present
        definition: "{{ lookup('file', 'service.yml') | replace ('TAG',version) }}"
        validate_certs: no
        namespace: default
    - name: Deploy the application
      k8s:
        state: present
        validate_certs: no
        namespace: default
        definition: "{{ lookup('file', 'deployment.yml') | replace ('TAG',version) }}"
