---
- hosts: masternode
  gather_facts: false
  remote_user: root
  vars:
    version: "{{version}}"
    ansible_ssh_private_key_file: "/var/lib/jenkins/.ssh/id_rsa"
  tasks:
    - name: Deploy the service
      k8s:
	apiVersion: v1
	kind: Service
        state: present
        validate_certs: no
        namespace: default
        metadata:
          name: hello-svc
        spec:
          selector:
            role: app
          ports:
            - protocol: TCP
              port: 80
              targetPort: 8080
              nodePort: 32000
          type: NodePort

    - name: Deploy the application
      k8s:
        state: present
        validate_certs: no
        namespace: default
        definition: "{{ lookup('file', 'deployment.yml') | replace ('TAG',version) }}"
